### ISSUE TITLE
Create a deployment process for redis_to_murko

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/mx-bluesky#672]
Following https://github.com/DiamondLightSource/mx-bluesky/pull/670 we deployed the service to i04's k8s cluster using:

* A new entrypoint
* A new `mx-bluesky` image that uses this endpoint
* A hacked `build_docker_image.sh` that pushed this image to a personal ghcr
* Using:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-to-murko
  labels:
    app: redis-to-murko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-to-murko
  template:
    metadata:
      labels:
        app: redis-to-murko
    spec:
      containers:
      - name: mx-bluesky
        image: ghcr.io/dominicoram/mx-bluesky:redis_to_murko_2
        env:
          - name: VALKEY_PASSWORD
            valueFrom:
             secretKeyRef:
               name: valkey-secret
               key: requirepass
        resources:
          requests:
            cpu: 30
            memory: 1Gi
          limits:
            cpu: 30
            memory: 1Gi
```
then:
```
kubectl create -f deploy.yaml
kubectl apply -f deploy.yaml
```

This needs to be formalised and made simpler.

## Acceptance Criteria
- There is an entrypoint for the service
- There is a generic `mx_bluesky` image that can be used for both of these but just different with different endpoints specified
- There are deployment scripts (helm charts?) for redis_to_murko
